import { useState, useEffect } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { apiClient } from "@/lib/api";
import { useStore } from "@/lib/store";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Form, FormItem, FormLabel, FormControl } from "@/components/ui/form";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { Sparkles, Plus, RefreshCw, Wrench } from "lucide-react";
import confetti from "canvas-confetti";

import { useTranslation } from "react-i18next";
import { DataTablePagination } from "@/components/ui/DataTablePagination";

function LiveStopwatch({ startTime }: { startTime?: string | number }) {
  const [seconds, setSeconds] = useState(0);

  useEffect(() => {
    const startMs = startTime ? new Date(startTime).getTime() : Date.now();
    const updateTimer = () => {
      const elapsed = Math.max(0, Math.floor((Date.now() - startMs) / 1000));
      setSeconds(elapsed);
    };
    updateTimer();
    const interval = setInterval(updateTimer, 1000);
    return () => clearInterval(interval);
  }, [startTime]);

  const mins = String(Math.floor(seconds / 60)).padStart(2, "0");
  const secs = String(seconds % 60).padStart(2, "0");

  return <span className="font-mono text-sm font-bold text-amber-900 dark:text-amber-300">{mins}:{secs}</span>;
}

function fireConfettiBlast() {
  confetti({
    particleCount: 100,
    spread: 70,
    origin: { y: 0.6 },
    colors: ["#38bdf8", "#0284c7", "#10b981", "#f59e0b", "#ec4899", "#8b5cf6"],
  });
}

function normalizeList(data: any) {
  if (Array.isArray(data)) return { items: data, total: data.length };
  if (data?.items) return data;
  return { items: [], total: 0 };
}

const STATUS_CONFIG: Record<string, { label: string; color: string; bg: string }> = {
  pending:     { label: "Pending",     color: "text-amber-700",  bg: "bg-amber-50 border-amber-200" },
  "in-progress": { label: "In Progress", color: "text-[#8B6748]", bg: "bg-[#F3EDE4] border-[#C4A882]" },
  clean:       { label: "Clean",       color: "text-green-700", bg: "bg-green-50 border-green-200" },
  inspected:   { label: "Inspected",   color: "text-violet-700", bg: "bg-violet-50 border-violet-200" },
};

function getRoomForTask(targetRoomId: any, allRooms: any[]) {
  if (targetRoomId == null) return null;
  const targetStr = String(targetRoomId).trim();
  return allRooms.find((r: any) =>
    String(r.id) === targetStr ||
    String(r.number) === targetStr ||
    String(r.room_number) === targetStr
  );
}

export default function HousekeepingPage() {
  const { t } = useTranslation();
  const storeRooms = useStore((state) => state.rooms);
  const updateRoomStatus = useStore((state) => state.updateRoomStatus);
  const [filterStatus, setFilterStatus] = useState("all");
  const [filterFloor, setFilterFloor] = useState("all");
  const [searchQuery, setSearchQuery] = useState("");
  const [page, setPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(8);
  const [dialogOpen, setDialogOpen] = useState(false);
  const qc = useQueryClient();

  const hkQ = useQuery({
    queryKey: ["housekeeping", filterStatus, filterFloor, searchQuery, storeRooms],
    queryFn: async () => {
      const [{ data: hkData }, { data: roomsData }] = await Promise.all([
        apiClient.housekeeping.list({ limit: 250 }),
        apiClient.rooms.list({ limit: 250 }),
      ]);
      const hkList = normalizeList(hkData).items;
      const apiRooms = normalizeList(roomsData).items;
      const allRooms = storeRooms.length > 0 ? storeRooms : apiRooms;

      // Housekeeping items are STRICTLY derived from rooms whose status is 'dirty' in the rooms table
      const activeDirtyList: any[] = [];

      allRooms.forEach((r: any) => {
        const roomStatus = r.status?.toLowerCase();
        
        // ONLY rooms whose status in the Rooms list is 'dirty' should appear in Housekeeping!
        if (roomStatus === "dirty") {
          const existingTask = hkList.find((t: any) =>
            String(t.roomId) === String(r.id) ||
            String(t.roomId) === String(r.number) ||
            String(t.roomId) === String(r.room_number)
          );

          activeDirtyList.push(existingTask || {
            id: `dirty-${r.id}`,
            roomId: r.id,
            status: "pending",
            assignedTo: "Maria Rodriguez",
            notes: "Room marked dirty - Turnaround cleaning required",
            isAutoGenerated: true,
          });
        }
      });

      let filtered = activeDirtyList;

      if (filterFloor !== "all") {
        filtered = filtered.filter((t: any) => {
          const roomObj = getRoomForTask(t.roomId, allRooms);
          return String(roomObj?.floor) === filterFloor;
        });
      }

      if (filterStatus !== "all") {
        filtered = filtered.filter((r: any) => r.status === filterStatus);
      }

      if (searchQuery) {
        filtered = filtered.filter((t: any) => {
          const roomObj = getRoomForTask(t.roomId, allRooms);
          const roomNum = roomObj?.number || roomObj?.room_number || String(t.roomId || "");
          return roomNum.toLowerCase().includes(searchQuery.toLowerCase()) || (t.assignedTo || "").toLowerCase().includes(searchQuery.toLowerCase());
        });
      }

      return filtered;
    },
  });

  const roomsQ = useQuery({
    queryKey: ["rooms-hk"],
    queryFn: async () => {
      const { data } = await apiClient.rooms.list({ limit: 250 });
      return normalizeList(data).items;
    },
  });

  const mainQ = useQuery({
    queryKey: ["maintenance-hk"],
    queryFn: async () => {
      const { data } = await apiClient.maintenance.list({ limit: 100 });
      return normalizeList(data).items;
    },
  });

  const form = useForm({
    defaultValues: { roomId: "", status: "pending", assignedTo: "", notes: "" },
  });

  const createM = useMutation({
    mutationFn: (d: any) => apiClient.housekeeping.create({ ...d, roomId: Number(d.roomId) || null }),
    onSuccess: (_, variables) => {
      qc.invalidateQueries({ queryKey: ["housekeeping"] });
      qc.invalidateQueries({ queryKey: ["rooms"] });
      qc.invalidateQueries({ queryKey: ["dashboard"] });
      apiClient.notifications.create({
        type: "housekeeping",
        title: "New Housekeeping Task",
        message: `Housekeeping task assigned for Room #${variables.roomId || 'General'}`,
      }).then(() => qc.invalidateQueries({ queryKey: ["notifications"] })).catch(() => {});
      toast.success(t("housekeeping.toastTaskCreated"));
      setDialogOpen(false);
      form.reset();
    },
    onError: (e: any) => toast.error(e?.response?.data?.error || t("housekeeping.toastFailed")),
  });

  const updateM = useMutation({
    mutationFn: async ({ id, data }: any) => {
      if (typeof id === "string" && id.startsWith("dirty-")) {
        const roomId = Number(id.replace("dirty-", ""));
        return apiClient.housekeeping.create({
          roomId,
          status: data.status || "in-progress",
          assignedTo: "Maria Rodriguez",
          notes: "Room marked dirty - Turnaround cleaning required",
        });
      }
      return apiClient.housekeeping.update(id, data);
    },
    onSuccess: (_, variables) => {
      qc.invalidateQueries({ queryKey: ["housekeeping"] });
      qc.invalidateQueries({ queryKey: ["rooms"] });
      qc.invalidateQueries({ queryKey: ["dashboard"] });
      const newStatus = (variables.data?.status || "updated").toUpperCase();
      apiClient.notifications.create({
        type: "housekeeping",
        title: `Housekeeping Alert`,
        message: `Housekeeping status updated to ${newStatus}`,
      }).then(() => qc.invalidateQueries({ queryKey: ["notifications"] })).catch(() => {});
      toast.success(t("housekeeping.toastStatusUpdated"));
    },
    onError: () => toast.error(t("housekeeping.toastFailedUpdate")),
  });

  const updateRoomM = useMutation({
    mutationFn: ({ roomId, status }: { roomId: number; status: string }) => {
      updateRoomStatus(roomId, status as any);
      return apiClient.rooms.update(String(roomId), { status, isAvailable: status === "vacant" || status === "clean" });
    },
    onSuccess: (_, variables) => {
      qc.invalidateQueries({ queryKey: ["rooms"] });
      qc.invalidateQueries({ queryKey: ["rooms-hk"] });
      qc.invalidateQueries({ queryKey: ["housekeeping"] });
      qc.invalidateQueries({ queryKey: ["dashboard"] });
      apiClient.notifications.create({
        type: "housekeeping",
        title: "Room Ready Status",
        message: `Room #${variables.roomId} status changed to ${variables.status.toUpperCase()}`,
      }).then(() => qc.invalidateQueries({ queryKey: ["notifications"] })).catch(() => {});
      toast.success(t("housekeeping.toastRoomStatusUpdated"));
    },
  });

  const items = hkQ.data ?? [];
  const allRooms = roomsQ.data ?? [];
  const maintItems = mainQ.data ?? [];

  return (
    <div className="space-y-6">
      {/* Top Header */}
      <div className="rounded-2xl bg-[#8B6748] text-white p-5 flex flex-wrap items-center justify-between gap-4 shadow-lg">
        <div className="flex items-center gap-3">
          <div className="h-10 w-10 rounded-xl bg-white/20 border border-white/30 flex items-center justify-center text-white">
            <Sparkles className="h-5 w-5" />
          </div>
          <div>
            <h1 className="text-xl font-bold">{t("housekeeping.title")}</h1>
            <p className="text-xs text-[#E8DED2]">{t("housekeeping.subtitle")}</p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <Button size="sm" onClick={() => { form.reset(); setDialogOpen(true); }} className="bg-white hover:bg-[#F3EDE4] text-[#8B6748] gap-2 rounded-xl font-bold shadow-md cursor-pointer">
            <Plus className="h-4 w-4" /> {t("common.create")}
          </Button>
        </div>
      </div>

      {/* Housekeeping Content */}
      <div className="space-y-6">
        <div className="space-y-6">
          {/* Filtering Bar */}
          <div className="rounded-2xl bg-card border border-border p-4 flex flex-wrap items-center justify-between gap-4">
            <div className="flex-1 min-w-[240px]">
              <Input
                placeholder={t("housekeeping.searchPlaceholder")}
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="bg-accent/40"
              />
            </div>
            <div className="flex flex-wrap items-center gap-3">
              <Select value={filterFloor} onValueChange={setFilterFloor}>
                <SelectTrigger className="w-36"><SelectValue placeholder={t("dashboard.allFloors")} /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">{t("dashboard.allFloors")}</SelectItem>
                  <SelectItem value="1">{t("dashboard.floor", { floor: 1 })}</SelectItem>
                  <SelectItem value="2">{t("dashboard.floor", { floor: 2 })}</SelectItem>
                  <SelectItem value="3">{t("dashboard.floor", { floor: 3 })}</SelectItem>
                  <SelectItem value="4">{t("dashboard.floor", { floor: 4 })}</SelectItem>
                </SelectContent>
              </Select>

              <Select value={filterStatus} onValueChange={setFilterStatus}>
                <SelectTrigger className="w-40"><SelectValue placeholder={t("housekeeping.allStatuses")} /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">{t("housekeeping.allStatuses")}</SelectItem>
                  <SelectItem value="pending">{t("housekeeping.dirtyPending")}</SelectItem>
                  <SelectItem value="in-progress">{t("housekeeping.inProgress")}</SelectItem>
                  <SelectItem value="clean">{t("housekeeping.clean")}</SelectItem>
                  <SelectItem value="inspected">{t("housekeeping.inspection")}</SelectItem>
                </SelectContent>
              </Select>

              <Button variant="outline" size="icon" onClick={() => qc.invalidateQueries({ queryKey: ["housekeeping"] })}>
                <RefreshCw className="h-4 w-4" />
              </Button>
            </div>
          </div>

          {/* Housekeeping Room Cards Grid / Empty State */}
          {items.length === 0 ? (
            <div className="rounded-3xl border border-dashed border-border bg-card/60 p-12 text-center space-y-3">
              <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-emerald-500/10 text-emerald-600">
                <Sparkles className="h-7 w-7" />
              </div>
              <h3 className="text-lg font-bold text-foreground">{t("housekeeping.noDirtyRooms")}</h3>
              <p className="text-xs text-muted-foreground max-w-sm mx-auto">
                {t("housekeeping.allRoomsClean")}
              </p>
            </div>
          ) : (
            <>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 sm:gap-5">
              {(itemsPerPage === 0 ? items : items.slice((page - 1) * itemsPerPage, page * itemsPerPage)).map((task: any) => {
                const roomObj = getRoomForTask(task.roomId, allRooms);
                const roomNum = roomObj?.number || roomObj?.room_number || String(task.roomId || "1001");
                const roomType = roomObj?.type || "King Suite";
                const floor = roomObj?.floor || 1;
                const status = task.status || "pending";
                const priority = task.priority || (status === "pending" ? "HIGH" : status === "in-progress" ? "HIGH" : "MEDIUM");

                return (
                  <div key={task.id} className="rounded-2xl border border-border/80 bg-card p-5 space-y-4 shadow-md hover:shadow-lg transition-all flex flex-col justify-between">
                    <div className="space-y-3">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <span className="text-lg font-black text-foreground">{t("roomDrawer.roomNumber", { number: roomNum })}</span>
                          <span className="text-xs text-muted-foreground font-semibold">({String(t("dashboard." + roomType.toLowerCase(), roomType))})</span>
                        </div>
                        <span className="text-xs text-muted-foreground font-mono">{t("dashboard.floor", { floor })}</span>
                      </div>

                      <div className="flex items-center justify-between text-xs pt-1">
                        <span className="font-semibold text-muted-foreground">{t("housekeeping.cleaningStatus")}</span>
                        {status === "pending" && (
                          <>
                            <span className="px-3 py-0.5 rounded-full text-xs font-bold bg-pink-500/15 text-pink-600 border border-pink-500/20 uppercase tracking-wider flex items-center gap-1">
                              <span className="h-1.5 w-1.5 rounded-full bg-pink-500"></span> {t("housekeeping.dirty")}
                            </span>
                          </>
                        )}
                        {status === "in-progress" && (
                          <>
                            <span className="px-3 py-0.5 rounded-full text-xs font-bold bg-amber-500/15 text-amber-600 border border-amber-500/20 uppercase tracking-wider flex items-center gap-1">
                              <span className="h-1.5 w-1.5 rounded-full bg-amber-500 animate-pulse"></span> {t("housekeeping.inProgressUpper")}
                            </span>
                          </>
                        )}
                        {status === "clean" && (
                          <>
                              <span className="px-3 py-0.5 rounded-full text-xs font-bold bg-[#8B6748]/15 text-[#8B6748] border border-[#8B6748]/20 uppercase tracking-wider flex items-center gap-1">
                              <span className="h-1.5 w-1.5 rounded-full bg-[#8B6748]"></span> {t("housekeeping.cleanUpper")}
                            </span>
                          </>
                        )}
                        {status === "inspected" && (
                          <>
                            <span className="px-3 py-0.5 rounded-full text-xs font-bold bg-purple-500/15 text-purple-600 border border-purple-500/20 uppercase tracking-wider flex items-center gap-1">
                              <span className="h-1.5 w-1.5 rounded-full bg-purple-500"></span> {t("housekeeping.inspectionUpper")}
                            </span>
                          </>
                        )}
                      </div>
                    </div>

                    <div className="p-3.5 rounded-xl bg-accent/40 text-xs text-muted-foreground leading-relaxed">
                      {(!task.notes || task.notes === "Room marked dirty - Turnaround cleaning required")
                        ? t("housekeeping.defaultNotes")
                        : task.notes === "Guest Checked Out - Express Checkout"
                          ? t("housekeeping.expressCheckoutNotes")
                          : task.notes}
                    </div>

                    <div className="border-t border-border pt-3 space-y-3">
                      <div className="flex items-center justify-between text-xs text-muted-foreground">
                        <span>{t("housekeeping.assignedStaffLabel")}</span>
                        <span className="font-bold text-foreground">{task.assignedTo || "Maria Rodriguez"}</span>
                      </div>

                      {status === "in-progress" && (
                        <div className="flex items-center justify-between p-2 rounded-xl bg-amber-500/10 border border-amber-500/20 text-xs font-bold text-amber-700 dark:text-amber-300">
                          <span className="flex items-center gap-1.5">
                            <span className="h-2 w-2 rounded-full bg-amber-500 animate-ping"></span> {t("housekeeping.liveCleaningTimer")}
                          </span>
                          <LiveStopwatch startTime={task.cleaningStartedAt || task.createdAt} />
                        </div>
                      )}

                      <div className="flex gap-2">
                        {status === "pending" && (
                          <Button
                            onClick={() => updateM.mutate({ id: task.id, data: { status: "in-progress", cleaningStartedAt: new Date().toISOString() } })}
                            className="flex-1 bg-[#8B6748] hover:bg-[#7A5A3C] text-white font-bold rounded-xl shadow-md py-2.5"
                          >
                            ▶ {t("housekeeping.startCleaning")}
                          </Button>
                        )}
                        {status === "in-progress" && (
                          <Button
                            onClick={() => {
                              fireConfettiBlast();
                              updateM.mutate({ id: task.id, data: { status: "clean" } });
                              if (task.roomId) {
                                updateRoomM.mutate({ roomId: Number(task.roomId), status: "vacant" });
                              }
                            }}
                            className="flex-1 bg-[#8B6748] hover:bg-[#7A5A3C] text-white font-bold rounded-xl shadow-md py-2.5"
                          >
                            ✓ {t("housekeeping.markCleanVacant")}
                          </Button>
                        )}
                        {status === "clean" && (
                          <Button
                            onClick={() => {
                              fireConfettiBlast();
                              updateM.mutate({ id: task.id, data: { status: "inspected" } });
                            }}
                            className="flex-1 bg-[#8B6748] hover:bg-[#7A5A3C] text-white font-bold rounded-xl shadow-md py-2.5"
                          >
                            🛡 {t("housekeeping.approveInspection")}
                          </Button>
                        )}
                        {status === "inspected" && (
                          <Button
                            onClick={() => updateM.mutate({ id: task.id, data: { status: "pending" } })}
                            className="flex-1 bg-[#8B6748] hover:bg-[#7A5A3C] text-white font-bold rounded-xl shadow-md py-2.5"
                          >
                            ↻ {t("housekeeping.markDirty")}
                          </Button>
                        )}
                        <Button variant="outline" size="icon" className="rounded-xl border-slate-300 dark:border-slate-700">
                          <Wrench className="h-4 w-4 text-[#8B6748]" />
                        </Button>
                      </div>
                    </div>
                  </div>
                );
              })}
              </div>

              {/* Pagination Controls */}
              <DataTablePagination
                currentPage={page}
                totalPages={itemsPerPage === 0 ? 1 : Math.ceil(items.length / itemsPerPage) || 1}
                totalItems={items.length}
                pageSize={itemsPerPage}
                onPageChange={setPage}
                onPageSizeChange={setItemsPerPage}
                pageSizeOptions={[8, 16, 24, 0]}
                itemName="tasks"
              />
            </>
          )}
        </div>
      </div>

      {/* New Task Dialog */}
      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader><DialogTitle className="text-2xl font-bold text-slate-900">{t("housekeeping.newTask")}</DialogTitle></DialogHeader>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(d => {
              if (!d.roomId || d.roomId === "") {
                toast.error(t("housekeeping.validationSelectRoom"));
                return;
              }
              if (!d.assignedTo || !d.assignedTo.trim()) {
                toast.error(t("housekeeping.validationStaffRequired"));
                return;
              }
              if (!d.notes || !d.notes.trim()) {
                toast.error(t("housekeeping.validationNotesRequired"));
                return;
              }
              createM.mutate(d);
            })} className="space-y-4 pt-2">
              <FormItem>
                <FormLabel className="font-semibold text-slate-800">{t("housekeeping.roomLabel")}</FormLabel>
                <FormControl>
                  <Select value={form.watch("roomId")} onValueChange={v => form.setValue("roomId", v)}>
                    <SelectTrigger><SelectValue placeholder={t("housekeeping.selectRoom")} /></SelectTrigger>
                    <SelectContent>
                      {allRooms.map((r: any) => (
                        <SelectItem key={r.id} value={String(r.id)}>{t("roomDrawer.roomNumber", { number: r.number || r.room_number })} ({String(t("dashboard." + (r.type || "Standard").toLowerCase(), r.type || "Standard"))})</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </FormControl>
              </FormItem>
              <FormItem>
                <FormLabel className="font-semibold text-slate-800">{t("housekeeping.assignedTo")}</FormLabel>
                <FormControl><Input placeholder={t("housekeeping.placeholderNotes")} {...form.register("assignedTo")} /></FormControl>
              </FormItem>
              <FormItem>
                <FormLabel className="font-semibold text-slate-800">{t("housekeeping.status")}</FormLabel>
                <FormControl>
                  <Select value={form.watch("status")} onValueChange={v => form.setValue("status", v)}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="pending">{t("housekeeping.dirtyPending")}</SelectItem>
                      <SelectItem value="in-progress">{t("housekeeping.inProgress")}</SelectItem>
                      <SelectItem value="clean">{t("housekeeping.clean")}</SelectItem>
                      <SelectItem value="inspected">{t("housekeeping.inspection")}</SelectItem>
                    </SelectContent>
                  </Select>
                </FormControl>
              </FormItem>
              <FormItem>
                <FormLabel className="font-semibold text-slate-800">{t("housekeeping.notesInstructions")}</FormLabel>
                <FormControl><Input placeholder={t("housekeeping.placeholderNotes")} {...form.register("notes")} /></FormControl>
              </FormItem>
              <div className="flex gap-3 justify-end pt-4">
                <Button type="button" variant="outline" className="h-11 rounded-2xl border-slate-200 bg-white hover:bg-slate-50 text-slate-700 font-medium px-6" onClick={() => setDialogOpen(false)}>
                  {t("common.cancel")}
                </Button>
                <Button type="submit" className="h-11 rounded-2xl bg-[#8B6748] hover:bg-[#7A5A3C] text-white font-semibold px-6" disabled={createM.isPending}>
                  {createM.isPending ? t("common.submitting") : t("housekeeping.saveTask")}
                </Button>
              </div>
            </form>
          </Form>
        </DialogContent>
      </Dialog>
    </div>
  );
}
